swagger: "2.0"
info:
    description: This is an example Koa API
    version: "1.0.0"
    title: "Swagger Example"
host: "localhost:4000"
schemes:
    - "http"
paths:
  /{tokenId}:
    get:
      summary: Get metadata assigned to this tokenId
      produces:
      - application/json
      parameters:
      - in: path
        name: tokenId
        type: integer
        minimum: 0
        required: true
        description: Numeric ID of token to get (that auto increments starting from 0)
      responses:
        200:
          description: A metadata has been created for that tokenId
        400:
          description: There is no metadata assigned to that tokenId
    post:
      summary: Create a new metadata assigned to tokenId
      consumes:
      - application/json
      parameters:
      - in: body
        name: metadataForNewTokenId
        schema:
          type: object
          required:
          - tokenId
          - result
          properties:
            tokenId:
              type: integer
              minimum: 0
            result:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                image:
                  type: string
                
              
              
      responses:
        201:
          description: tokenId has not been already assigned to any metadata, and we Created new assignment
        400:
          description: There is an existing metadata assigned to that tokenId